product-name = "Rusty Alto"
identifier = "org.rustyalto.workbench"
before-packaging-command = "cargo build --release"
out-dir = "dist"
icons = [
  "assets/icons/32x32.png",
  "assets/icons/128x128.png",
  "assets/icons/128x128@2x.png",
  "assets/icons/icon.icns",
  "assets/icons/icon.ico",
]
